#!/usr/bin/env python3
"""
Step 3 of the stock-face build: pick the faces that actually make good spare
parts, and write the library the app ships.

Selection is by hand rather than by score, because the criteria are things no
cheap metric captures: adults only, eyes unobstructed, an expression that still
reads as a face when only the mouth is borrowed, and lighting flat enough that
the piece can be colour-matched onto somebody else.

Vividly dyed hair is excluded for a specific reason: a brow piece carries a
sliver of the hair above it, and a streak of electric blue in one of six
otherwise-plausible eyebrows hands the answer straight to the player.

Usage:  python3 curate_stock.py <stock-raw-dir> <out-dir>
"""
import json, pathlib, shutil, sys

# Labels as they appear on the contact sheet, decoded below.
KEEP = [
    # sheet             note for the curator's own memory
    'Accessories.0006',  # older woman, neutral
    'Accessories.0103',  # woman, neutral
    'Accessories.0203',  # young man, neutral
    'Accessories.0500',  # woman, neutral
    'Accessories.0501',  # woman, braids
    'Age.0401',          # man, beard
    'Age.0404',          # man, clean shaven
    'Age.0408',          # man, stubble
    'Age.0500',          # very old man
    'Age.0501',          # old man
    'Age.0503',          # old woman
    'Age.0507',          # old woman
    'Age.0509',          # old woman
    'Expression_x_Sex.0200',  # smiling man
    'Expression_x_Sex.0201',  # smiling man
    'Expression_x_Sex.0202',  # smiling man
    'Expression_x_Sex.0205',  # man, dreadlocks
    'Hair_Color.0005',   # older woman, short grey
    'Hair_Color.0007',   # older woman
    'Hair_Color.0009',   # older woman, grey
    'Hair_Color.0505',   # woman, red hair
    'Lighting.0100',     # woman, soft light
    'Lighting.0608',     # woman
]


def decode(label):
    """'Age.0401' -> 'Age_r04c01'. The sheet labels drop the r/c separators."""
    stem, digits = label.rsplit('.', 1)
    return f'{stem}_r{digits[:2]}c{digits[2:]}'


def main():
    src = pathlib.Path(sys.argv[1])
    out = pathlib.Path(sys.argv[2])
    out.mkdir(parents=True, exist_ok=True)

    index = {r['id']: r for r in json.loads((src / 'manifest.json').read_text())}

    faces, missing = [], []
    for n, label in enumerate(KEEP, start=1):
        key = decode(label)
        record = index.get(key)
        if not record:
            missing.append(f'{label} -> {key}')
            continue
        face_id = f's{n:02d}'
        shutil.copy(src / f'{key}.webp', out / f'{face_id}.webp')
        faces.append(dict(id=face_id, file=f'{face_id}.webp',
                          rel=record['rel'], tone=record['tone']))

    manifest = dict(
        version=1,
        note=('Synthetic faces. Nobody in this library is a real person: every image was '
              'generated by a text-to-image model. Sourced from the SFHQ-T2I dataset '
              '(github.com/SelfishGene/SFHQ-T2I-dataset, MIT, (c) 2024 David Beniaguev), '
              'then aligned and cropped by tools/build_stock_faces.py.'),
        size=512,
        faces=faces,
    )
    (out / 'manifest.json').write_text(json.dumps(manifest, indent=1))

    print(f'wrote {len(faces)} faces')
    if missing:
        print('MISSING:', *missing, sep='\n  ')


if __name__ == '__main__':
    main()
